### ISSUE TITLE
PHP 8.1 Errors

### ISSUE THREAD

**Issue by drewdeakin** [CleanTalk/php-antispam#32]
When trying to execute a call, the following errors are coming up:

Deprecated: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /vendor/cleantalk/php-antispam/lib/CleantalkHelper.php on line 328

Deprecated: Implicit conversion from float 207.1 to int loses precision in /vendor/cleantalk/php-antispam/lib/Cleantalk.php on line 543

Deprecated: Implicit conversion from float 332.2 to int loses precision in /vendor/cleantalk/php-antispam/lib/Cleantalk.php on line 543

Deprecated: Implicit conversion from float 147.2 to int loses precision in /vendor/cleantalk/php-antispam/lib/Cleantalk.php on line 543

Deprecated: Implicit conversion from float 296.09999999999997 to int loses precision in /vendor/cleantalk/php-antispam/lib/Cleantalk.php on line 543

Deprecated: Implicit conversion from float 296.20000000000005 to int loses precision in /vendor/cleantalk/php-antispam/lib/Cleantalk.php on line 543

Deprecated: Implicit conversion from float 294.4 to int loses precision in /vendor/cleantalk/php-antispam/lib/Cleantalk.php on line 543

Deprecated: preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /vendor/cleantalk/php-antispam/lib/CleantalkResponse.php on line 149

**Comment by alexandergull** [comment]
Hello.

These messages are deprecation notices, not errors. 

We have fixed these notices in the dev branch.

https://github.com/CleanTalk/php-antispam/commit/c33f54a93299e08b4f93a8704afd07ddef8d5c6c

https://github.com/CleanTalk/php-antispam/commit/178507446d2b2927169709ce64507060424ebdde

Try to check out this one instead of master branch.

https://github.com/CleanTalk/php-antispam/tree/dev

Thank you for your help.
